version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend:latest
    container_name: frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend:latest
    container_name: backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
      - frontend

  gateway:
    image: ${DOCKER_USERNAME}/kittygram_gateway:latest
    container_name: gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
